### PR TITLE
Fix config variable scope issue in Vagrantfile

### PR DESCRIPTION
**Pull request by jeffmccune**
Should be cfg for a specific VM configuration, config is the "global"
virtualbox configuration.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Could you please elaborate on the issue that this fixes?

**Comment by jeffmccune** [comment]
@ghoneycutt 

> Could you please elaborate on the issue that this fixes?

The problem is that the code I wrote for rizzo was using `config` and `cfg` willy-nilly inside a VM configuration.   `config` is the global configuration. meant to be the default for all VM's.  A specific VM shouldn't be modifying `config`, and instead should modify a local variable `cfg`.

**Comment by jeffmccune** [comment]
@ghoneycutt All green now.

**Comment by ghoneycutt** [comment]
Thanks @jeffmccune !

**Comment by ghoneycutt** [comment]
Released in v0.6.0

**Pull request merged**
