### PR TITLE
Box validation

### LINKED ISSUE #35: Ensure that options with the value `nil` are not added to Vagrantfile
If a value is `nil` it will be incorrectly added with a line such as

`"box_url": = nil`

when it should just not add the config option.

### PR DESCRIPTION
**Pull request by treydock**
Ensure `box` is defined for all nodes after defaults and node definitions are merged.  This addresses #36.

Also more work to ensure `nil` values are not put into the Vagrantfile which should resolve #35

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Awesome work!

The functional test should show that with invalid nodes it will throw an error and exit non-zero.

**Comment by treydock** [comment]
Updated functional tests.  The `opts` in `validate_inform!` appeared to always be undefined so allowed `opts` to be defined as before this change the Vagrantfile wouldn't get generated and exit status was still 0.  Now exit code is 2 if nodes are invalid.

**Comment by treydock** [comment]
Spoke too soon, `set -e` is causing some problems, trying to fix.

**Comment by treydock** [comment]
Fixed, had to disable `set -e` during expected command failure.

**Pull request merged**
